apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pier-data
  namespace: pier
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  # storageClassName: longhorn   # uncomment + set to your cluster's default
