apiVersion: v1
kind: Service
metadata:
  name: pier
  namespace: pier
  labels:
    app.kubernetes.io/name: pier
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pier
  ports:
    - name: http
      port: 8420
      targetPort: http
